services:
  postgresql-db:
    image: postgres:18
    container_name: entropy_users_postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: entropy_users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  entropy-backend-ms-users:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: entropy_backend_ms_users
    depends_on:
      - postgresql-db
    ports:
      - "3001:3001"
    volumes:
      - .:/app

volumes:
  postgres_data: