listen_addresses = '*'
max_connections = 100			# (change requires restart)

shared_buffers = 128MB			# min 128kB
#max_stack_depth = 2MB			# min 100kB
dynamic_shared_memory_type = posix	# the default is usually the first option

wal_level = logical			# minimal, replica, or logical

max_wal_size = 1GB # Max size to let WAL grow between automatic checkpoints.  This is not a hard limit, but a target for checkpointing.
min_wal_size = 80MB # Min size to shrink WAL to during automatic checkpointing.  This is not a hard limit, but a target for checkpointing.

max_wal_senders = 10		# max number of walsender processes
max_replication_slots = 10	# max number of replication slots
wal_keep_size = 0		# in megabytes; 0 disables
max_slot_wal_keep_size = -1	# in megabytes; -1 disables
idle_replication_slot_timeout = 0	# in seconds; 0 disables
wal_sender_timeout = 60s	# in milliseconds; 0 disables
track_commit_timestamp = off	# collect timestamp of transaction commit

# synchronous_standby_names = ''	# standby servers that provide sync rep
# synchronized_standby_slots = ''	# streaming replication standby server slot

log_timezone = 'Etc/UTC'

autovacuum_worker_slots = 16		# autovacuum worker slots to allocate

datestyle = 'iso, mdy'
timezone = 'Etc/UTC'

lc_messages = 'en_US.utf8'		# locale for system error message
lc_monetary = 'en_US.utf8'		# locale for monetary formatting
lc_numeric = 'en_US.utf8'		# locale for number formatting
lc_time = 'en_US.utf8'			# locale for time formatting

default_text_search_config = 'pg_catalog.english'
